apiVersion: skaffold/v1beta13
build:
  artifacts:
  - context: .
    docker:
      dockerfile: Dockerfile
    image: gcr.io/triple-bounty-295104/tfx-pipeline
  tagPolicy:
    envTemplate:
      template: latest
kind: Config
